# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ekliot
email: ekliot@gmail.com
description: The landing page for everything of Elijah Kliot's
url: "https://www.ekliot.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

excerpt_seperator: "<!-- more -->"
paginate_path: "/pg:num"

#sass
sass:
  sass_dir: _sass
  style:    compressed

# asset dirs
script_dir: assets/scripts
media_dir:  assets/media
image_dir:  assets/media/images
video_dir:  assets/media/videos
pdf_dir:    assets/media/pdfs

markdown: kramdown

# collections config
collections:
  posts:
    permalink: /log/:year/:month/:slug
    output: true
  projects:
    permalink: /makes/:title
    output: true

roots:
  -
    label: 'home'
    url: ''
  - projects
  - log
  - about
  - contact

# site defaults
defaults:
  -
    scope:
      path: ""
    values:
      author: "ekliot"
  -
    scope:
      path: "_projects"
    values:
      layout: "project"
      category: "projects"
      root: projects
  # -
  #   scope:
  #     path: "_posts"
  #   values:
  #     layout: "post"
  #     category: "posts"
  #     root: "log"

# # jekyll-archive vars
# jekyll-archives:
#   enabled:
#     - year
#     - month
#     - tags
#   layouts:
#     year:  archive-year
#     month: archive-month
#     tag:   archive-tag
#   permalinks:
#     year:  '/posts/:year/'
#     month: '/posts/:year/:month/'
#     tag:   '/posts/tag/:name/'

# # jekyll-seo-tag vars
# twitter:
#   username: ekliot
# social:
#   name: Elijah Kliot
#   links:
#     - https://github.com/ekliot
#     - https://twitter.com/ekliot
#     - https://www.linkedin.com/in/ekliot

# Build settings
incremental: true
future: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
